apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-1-depl
  template:
    metadata:
      labels:
        app: nginx-1-depl
    spec:
      containers:
      - name: nginx
        image: nginx
