apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-1-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-1-rs
  template:
    metadata:
      labels:
        app: nginx-1-rs
    spec:
      containers:
      - name: nginx
        image: nginx
